### ISSUE TITLE
unknown command "all" for "kubeaudit"

### ISSUE THREAD

**Issue by shane-lawrence** [Shopify/kubeaudit#100]
Running `kubeaudit all` should perform all available audits, but the command is not recognized.

```
➜  ./kubeaudit -l all
Error: unknown command "all" for "kubeaudit"

Did you mean this?
    allowpe
```

**Comment by jinankjain** [comment]
Hey @shane-lawrence 👋  I just checked that command and its working for me. May be you are running an old binary, can you check the git log? (Latest version is 987d36f9a096fcf4fb4d3c82e30936e1346fdff0) 😄

**Comment by shane-lawrence** [comment]
Rebuilt the binary and it's working now. Thanks!

**Comment by gytisgreitai** [comment]
@jinankjain `all` is not supported in the official release `kubeaudit-v0.2.0`. So probably the preferred installation should be switched from `Download a binary` to `DIY build`
