### ISSUE TITLE
Version Command Panics

### ISSUE THREAD

**Issue by shane-lawrence** [Shopify/kubeaudit#112]
`kubeaudit version` returns the wrong version number and then panics.

```
INFO[0000] Kubeaudit                                     Version=0.1.0
Running inside cluster, using the cluster config
ERRO[0000] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1059878]
```

**Comment by jinankjain** [comment]
@shane-lawrence one solution could be that by default set the value of local to be true and use special flag to indicate its inside a cluster. 

On a side note I think we need to change that version string too.

**Comment by shane-lawrence** [comment]
The version string needs to be updated and I noticed a few times that the kubectl client version was blank so I'll look into that as well.

Here's my proposed fix for the panic: https://github.com/Shopify/kubeaudit/pull/113

**Comment by shane-lawrence** [comment]
Resolved by https://github.com/Shopify/kubeaudit/pull/113.
