### ISSUE TITLE
NetworkPolicy check not implemented?

### ISSUE THREAD

**Issue by johscheuer** [Shopify/kubeaudit#117]
In https://github.com/Shopify/kubeaudit#audit-network-policies is the following describe:

```bash
It checks that every namespace should have a default deny network policy installed. 
See Kubernetes Network Policies for more information:
```

But actually the code https://github.com/Shopify/kubeaudit/blob/master/cmd/networkPolicies.go only iterates over existing `networkPolicies` and doesn't check if the `default-deny` policy is set. Also currently only the default `allow all` policy is checked (which leads to an warning).

**Comment by TheKangaroo** [comment]
Thank you for the PR @johscheuer, exactly what I was looking for 😍

**Comment by TheKangaroo** [comment]
Is there an estimated time when this feature will be in a release? :)

**Comment by nschhina** [comment]
@johscheuer can we close this issue now? @TheKangaroo it should be in v0.4.x now
