### ISSUE TITLE
Which Kubernetes versions are supported?

### ISSUE THREAD

**Issue by luarx** [Shopify/kubeaudit#126]
I want to know which specific Kubernetes versions are supported

For example, I am using the **apps/v1** (from kubernetes v1.9) resource type for Deployments but I can not check it because the tool don't support it...

**Will it be supported soon**?

Thank you very much for this helpful tool!

**Comment by johscheuer** [comment]
You can take a look here: https://github.com/Shopify/kubeaudit/blob/master/cmd/types.go actually the question is not "which Kubernetes versions are supported" rather it's "which api-resources are supported". It should be pretty straight forward to add support for `apps/v1` (the biggest part is probably to add some additional test cases).

**Comment by luarx** [comment]
Yes! I agree with you, the question "which api-resources are supported" is more correct!

Oh I understand, it could be added apps/v1 support without those additional test cases because app/v1 is an api that it's available since k8s-v1.9 and it's one of the most used nowadays... or it could not be added if we don't want to enable support for this without having all the additional test cases available so that users don't think that they have tested everything.

It depends on what it's this repo "philosophy"...

What do you think?
