### ISSUE TITLE
RunAsNonRoot can be inherited from PodSecurityContext

### ISSUE THREAD

**Issue by nrvnrvn** [Shopify/kubeaudit#138]
Current check covers only Container SecurityContext, but `RunAsNonRoot`, `RunAsUser`, `RunAsGroup` and `SELinuxOptions` are all inherited from the PodSecurityContext unless they are defined explicitly container-wise. 

Please consider adding `PodSecurityContext` to the list of checked values.

Ref:
https://github.com/Shopify/kubeaudit/blob/87446f2a54a1c25e280697468fdfbf1b39d98517/cmd/runAsNonRoot.go#L10

**Comment by klautcomputing** [comment]
What's the difference between https://github.com/Shopify/kubeaudit/issues/123 and this? Asking because you 👍 'd the other and opened this.

**Comment by nrvnrvn** [comment]
PodSecurityPolicy and PodSecurityContext are different things :)
