### ISSUE TITLE
Decouple Result from logrus's StandardLogger

### ISSUE THREAD

**Issue by catherinejones** [Shopify/kubeaudit#169]
##### ISSUE TYPE
 - [X] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
`Result` is currently heavily tied to the `logrus.StandardLogger`, which means that testing it requires dealing with it being a global variable. Decoupling `logrus.StandardLogger` from `Result` would simplify testing the output of Kubeaudit.

- [X] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Comment by nschhina** [comment]
Thank you so much Catherine for taking this issue up! Looking forward to the PR

**Comment by catherinejones** [comment]
I suspect that this will be resolved as a result of @genevieveluyt's refactor of the Kubeaudit code base, so I'm going to close this for now.
