### ISSUE TITLE
Versioning/Releases and Tags

### ISSUE THREAD

**Issue by klautcomputing** [Shopify/kubeaudit#2]
:wave: @jinankjain @JonPulsifer 

Do we want to version kubeaudit? 
 - [x] Create releases and tags in Github
 - [x] add a flag to the kubeaudit binary that reports the current version.

So that you can install specific version via e.g. glide and check which version is currently install with e.g. `--version`.

**Comment by jinankjain** [comment]
@klautcomputing How do we name the version like v1.0.0 or v0.0.1?

**Comment by JonPulsifer** [comment]
How do you feel about using https://github.com/goreleaser/goreleaser ?

**Comment by klautcomputing** [comment]
https://github.com/Shopify/kubeaudit/pull/9 adds the flag to kubeaudit

**Comment by klautcomputing** [comment]
https://github.com/Shopify/kubeaudit/pull/3 adds goreleaser

**Comment by klautcomputing** [comment]
last(?) but not least: @jinankjain suggested to use: https://github.com/hashicorp/go-version

**Comment by jinankjain** [comment]
This can be closed now with #14 #9 #6 #7 @klautcomputing

**Comment by klautcomputing** [comment]
Yes :)
