### ISSUE TITLE
[feature] how to automate the scan through cronjob ?

### ISSUE THREAD

**Issue by jonny-wg2** [Shopify/kubeaudit#218]
##### ISSUE TYPE
 - [ ] Bug Report
 - [x] Feature Idea

# FEATURE IDEA

**Proposal:**
It would be great to have a way to run this tool in an automated form within k8 cluster.

<sup><small>1</small></sup> <sub>This is the quickest way to get a new feature! We reserve the right to close feature requests, even ones we like, if the proposer does not intend to contribute to the feature and it doesn't fit in our current roadmap.</sub>

**Comment by genevieveluyt** [comment]
Hi @jonny-wg2, thanks for submitting a feature idea!

Kubeaudit does already support auditing a cluster (if kubeaudit detects that it's running in a container, kubeaudit will attempt to audit the cluster it's running in). You could have a look at https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/.

Cronjob automation is not something we want to build into kubeaudit at this time but let me know if you need help getting it up and running!
