### ISSUE TITLE
go get -v doesn't work against master

### ISSUE THREAD

**Issue by raesene** [Shopify/kubeaudit#224]
##### ISSUE TYPE
 - [X ] Bug Report

# BUG REPORT

##### SUMMARY
Following the source installation process fails

##### ENVIRONMENT
* Kubeaudit version: master
* Kubeaudit install method: DIY-BUILD

##### STEPS TO REPRODUCE

Run `go get -v github.com/Shopify/kubeaudit`

##### EXPECTED RESULTS

the application downloads/compiles.

##### ACTUAL RESULTS

`github.com/Shopify/kubeaudit/scheme/register.go:54:21: cannot use "github.com/jetstack/cert-manager/pkg/apis/certmanager/v1alpha1".AddToScheme (type func(*"github.com/jetstack/cert-manager/vendor/k8s.io/apimachinery/pkg/runtime".Scheme) error) as type func(*"k8s.io/apimachinery/pkg/runtime".Scheme) error in array or slice literal`

##### ADDITIONAL INFORMATION

`go version go1.10.4 linux/amd64`

**Comment by nschhina** [comment]
Although I'm not sure of this but Kubeaudit transitioned away to using go modules, concept of `$GOPATH` is not relevant anymore and that might be causing problems with go get as kubeaudit uses a custom fork/clone of the v1alpha1 library to support custom resources. Please investigate further @genevieveluyt @klautcomputing , if need be I'd suggest removing `go get` install method altogether from the docs

**Comment by vvuibert** [comment]
`go version go1.12.7 darwin/amd64` same error

**Comment by genevieveluyt** [comment]
I am going to remove it from the readme for now and investigate
