### ISSUE TITLE
Create Audit for AllowPrivilegeEscalation

### ISSUE THREAD

**Issue by JonPulsifer** [Shopify/kubeaudit#23]
ref https://github.com/kubernetes/kubernetes/pull/47019

in 1.8 we now have the ability to define `allowPrivilegeEscalation: false` in our container security contexts

let's audit for this @klautcomputing 👍

**Comment by jinankjain** [comment]
Seems like it has not been added to PodSecurityContext in `api` yet https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4763

**Comment by klautcomputing** [comment]
That's why I asked Jon to create this issue :) So that we have this to-do to come back to it one day.

**Comment by jinankjain** [comment]
I created an issue on `kubernetes/api` https://github.com/kubernetes/api/issues/8 too

**Comment by jinankjain** [comment]
@JonPulsifer @klautcomputing It is supported by client-go now
