### ISSUE TITLE
error with custom resources

### ISSUE THREAD

**Issue by vvuibert** [Shopify/kubeaudit#233]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
we use [statefulservice](https://github.com/Shopify/cloudbuddies/blob/master/apis/shopify/v1/statefulservice.go) which is a custom resource and `kubeaudit` throughs an error instead of a warning since it's not supported

##### ENVIRONMENT
* Kubeaudit version: 0.0.0
* Kubeaudit install method: DIY-BUILD

##### STEPS TO REPRODUCE
`kubeaudit autofix -f config/deploy/staging/kafka.yml`
https://github.com/Shopify/kafka-infrastructure/blob/master/config/deploy/staging/kafka.yml

##### EXPECTED RESULTS

WARN Skipping unsupported resource type Statefulservice

##### ACTUAL RESULTS
```
kubeaudit autofix -f config/deploy/staging/kafka.yml
WARN[0000] Skipping unsupported resource type /v1, Kind=Service
WARN[0000] Skipping unsupported resource type /v1, Kind=Service
WARN[0000] Skipping unsupported resource type policy/v1beta1, Kind=PodDisruptionBudget
ERRO[0000] File is not a valid Kubernetes manifest: no kind "Statefulservice" is registered for version "stable.shopify.io/v1" in scheme "pkg/runtime/scheme.go:101"
```

##### ADDITIONAL INFORMATION

# FEATURE IDEA

- [ ] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Proposal:** 

<sup><small>1</small></sup> <sub>This is the quickest way to get a new feature! We reserve the right to close feature requests, even ones we like, if the proposer does not intend to contribute to the feature and it doesn't fit in our current roadmap.</sub>

**Comment by genevieveluyt** [comment]
This should be fixed by #243. Please re-open if the problem remains
