### ISSUE TITLE
Return other exit code on error

### ISSUE THREAD

**Issue by ppawiggers** [Shopify/kubeaudit#257]
##### ISSUE TYPE
 - [ ] Bug Report
 - [x] Feature Idea

# BUG REPORT

##### SUMMARY
I use kubeaudit to audit a Kubernetes manifest. I'd like to run this during CI. If kubeaudit finds and error, it should return an exit code other than 0, to indicate that it failed.

##### ENVIRONMENT
* Kubeaudit version: 0.7.0
* Kubeaudit install method: Binary

##### STEPS TO REPRODUCE
    kubeaudit all -f manifest.yaml
    > ERRO[0000] AppArmor annotation missing.                  Container=foo KubeType=deployment Name=foo Namespace=foo
    echo $?
    > 0

##### EXPECTED RESULTS
exit code 1 or 2

##### ACTUAL RESULTS
exit code 0

**Comment by nschhina** [comment]
@klautcomputing

**Comment by J12934** [comment]
Would bve cool if this would be a optional feature, or at least could be disabled via a command line flag, as this would make running kubeaudit in a Kubernetes Job harder.
