### ISSUE TITLE
Disable line wrapping

### ISSUE THREAD

**Issue by genevieveluyt** [Shopify/kubeaudit#272]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
Turn off automatic line wrapping. Now that https://github.com/go-yaml/yaml/pull/455 has been closed we can finally do this 🎉 

##### STEPS TO REPRODUCE

Run kuebaudit on a manifest with a long line

##### EXPECTED RESULTS

Long lines should not be automatically wrapped.

##### ACTUAL RESULTS

Long lines are automatically wrapped

**Comment by dani-santos-code** [comment]
@genevieveluyt 

I tried reproducing the bug, but wasn't able to. :( 

I ran `./kubeaudit autofix -f` and passed in the manifest path. I added a very long line and it didn't change anything. Anything I'm missing?

**Comment by genevieveluyt** [comment]
I couldn't replicate it either so I'm going to close this issue 😄
