### ISSUE TITLE
nonintuitive documentation on the configuration of OverrideLabels

### ISSUE THREAD

**Issue by smijolovic** [Shopify/kubeaudit#273]
Attempting to audit a configuration of a kubernetes cluster has various requirements that violate the audit policies, so it makes sense to override them. However, the documentation really doesn't make the syntax of a config file clear at all. 

Attempting for example to Override allow-privileged for the kube-proxy container/pod does not work:

apiVersion: v1
kind: kubeauditConfig
audit: true
spec:
   template:
   metadata:
   labels:
       apps: kube-proxy
       audit.kubernetes.io/pod.allow-privileged: "Kube-proxyNeedsIPtables"
       container.audit.kubernetes.io/kube-proxy.allow-privileged: "Kube-proxyNeedsIPtables"

Running the command:
kubectl audit priv -c /etc/kubernetes/admin.conf -k ./kubeaudit.yaml -n kube-system

Still produces:
ERRO[0000] Privileged set to true! Please change it to false!  Container=kube-proxy KubeType=daemonSet Name=kube-proxy Namespace=kube-system
ERRO[0000] Privileged set to true! Please change it to false!  Container=kube-proxy KubeType=pod Name=kube-proxy-qzhbv Namespace=kube-system

What is the proper way to write an actual configuration override?

**Comment by genevieveluyt** [comment]
Hi @smijolovic ,

You can refer to the documentation for the next release as the override behaviour is the same https://github.com/Shopify/kubeaudit/tree/release#override-errors. Basically the label needs to be on the individual resources, not in the global config. I wonder if it makes sense to add support for an "exclude namespaces" list in the global config?

**Comment by genevieveluyt** [comment]
The new release is out so the override errors documentation can be found at https://github.com/Shopify/kubeaudit#override-errors. I an closing this issue but if you find the documentation is still confusing, please feel free to re-open.
