### ISSUE TITLE
Migrate to `installation` webhook events

### ISSUE THREAD

**Issue by Nilay-Shah** [Shopify/kubeaudit#279]
This may or may not be a no-op, but we need to migrate to listening for `installation` type events instead of `integration_installation` as `integration_installation` webhook events will be deprecated!

More info in Githubs blog post: https://developer.github.com/changes/2020-04-15-replacing-the-installation-and-installation-repositories-events/

**Comment by genevieveluyt** [comment]
Pretty sure this is a no op, we don't do anything with the Github API in this repo
