### ISSUE TITLE
Introduce logging level in kubeaudit

### ISSUE THREAD

**Issue by jinankjain** [Shopify/kubeaudit#28]
In the current scenario kubeaudit emit logs when there is an error/warning but there might be other use cases.

Like getting more information about the healthy k8s resources like the once which are not violating any security policies laid out by kubeaudit.

So for this we need to have different log level for example:

INFO: This would be the most verbose log level
ERROR/WARNING: This would be default log level

@klautcomputing

**Comment by klautcomputing** [comment]
Sounds good. I think we should introduce a new option for this like: `--log-level=INFO` for that.
Do we want to introduce something like `result.info`?

**Comment by jinankjain** [comment]
I think you can just configure logrus depending upon that flag to emit different output

**Comment by JonPulsifer** [comment]
I like this idea, although instead of introducing a new flag like `--log-level` I think we should stick with the conventions followed in other kubernetes command line tools like `-v=9` or something?

We already have a verbose flag `-v` so?

**Comment by klautcomputing** [comment]
#36 closes this
