### ISSUE TITLE
Warn if the container referenced by the apparmor annotation doesn't exist

### ISSUE THREAD

**Issue by genevieveluyt** [Shopify/kubeaudit#285]
##### ISSUE TYPE
 - [ ] Bug Report
 - [x] Feature Idea

# FEATURE IDEA

If an apparmor annotation references a container which doesn't exist, the manifest will fail to apply (assuming AppArmor is enabled in the cluster). Kubeaudit can produce a warning about this case

**Comment by genevieveluyt** [comment]
Fixed by #286

**Comment by thriqon** [comment]
This fix breaks `initContainers`, doesn't it? Or have I missed something?

**Comment by genevieveluyt** [comment]
@thriqon could you give an example of how this would break `initContainers`?
