### ISSUE TITLE
K8s 1.6+: Incorrect 'Default service account with token mounted'

### ISSUE THREAD

**Issue by christophetd** [Shopify/kubeaudit#290]
##### ISSUE TYPE
 - [x] Bug Report

# BUG REPORT

##### SUMMARY

kubeaudit reports `AutomountServiceAccountTokenTrueAndDefaultSA` even if the service account spec has `"automountServiceAccountToken": false`, as available in K8s 1.6+ (see https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server)

##### ENVIRONMENT
* Kubeaudit version: v0.9.0
* Kubeaudit install method: DIY build

##### STEPS TO REPRODUCE

- Notice that by default, the `default` service account token is mounted in pods

```
$ kubectl run --rm -i --tty shell --image=alpine --restart=Never -- ls /var/run/secrets/kubernetes.io/serviceaccount/
ca.crt     namespace  token
```

- Patch the default service account so it doesn't automatically mount service account tokens in pods:

```
$ kubectl patch serviceaccount default -p '{"automountServiceAccountToken": false}'
```

- Start a pod, and notice the service account token isn't mounted anymore:

```
$ kubectl run --rm -i --tty shell --image=alpine --restart=Never -- ls /var/run/secrets/kubernetes.io/serviceaccount/
ls: /var/run/secrets/kubernetes.io/serviceaccount/: No such file or directory
```

- Notice that `kubeaudit asat` still complains about a service account token being automatically mounted:

```
$ kubeaudit asat
ERRO[0000] Default service account with token mounted. automountServiceAccountToken should be set to 'false' or a non-default service account should be used.  AuditResultName=AutomountServiceAccountTokenTrueAndDefaultSA
```

##### EXPECTED RESULTS

No output from kubeaudit, as the default service account token is not mounted

**Comment by christophetd** [comment]
Looks great! Would it be possible to have a release or release candidate to beneficial from the fix?

**Comment by genevieveluyt** [comment]
Yes, I will make a release as soon as the docs are updated (https://github.com/Shopify/kubeaudit/pull/299). Should be today or Monday at the latest!

**Comment by genevieveluyt** [comment]
Release is out now 🙂
