### ISSUE TITLE
Support for Openshift CRDs

### ISSUE THREAD

**Issue by CurryWurry** [Shopify/kubeaudit#292]
##### ISSUE TYPE
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
Are there any plans to implement support for Openshift CRDs ?

##### ENVIRONMENT
* Kubeaudit version: 0.11.0
* Kubeaudit install method: Binary

##### STEPS TO REPRODUCE

Try to audit an Openshift DeploymentConfig manifest:
$> kubeaudit -all -f /home/user/deploymentconfig.yml

##### EXPECTED RESULTS
see a report with errors/warning for the manifest

##### ACTUAL RESULTS
no results are being displayed.

**Comment by genevieveluyt** [comment]
Hi @CurryWurry , I'm not too familiar with OpenShift but from a quick Google search it looks like these are just custom Kubernetes resources (not specific to OpenShift). Is that right? Or are there some custom resources that OpenShift provides? Do you have an example? What do you imagine supporting these resources would look like?

**Comment by CurryWurry** [comment]
hi @genevieveluyt , Openshift indeed provides some custom resources, some of which are quite similar to their K8 counterparts. For example:

- DeploymentConfig (apiVersion: apps.openshift.io/v1): very similar to Deployment, but with added "triggers" sections
- ImageStream (apiVersion: image.openshift.io/v1): indirection layer for Images
- Route (apiVersion: route.openshift.io/v1): similar to Ingress
- Project (apiVerison: project.openshift.io/v1): basically a namespace with added annotations

Openshift shares a lot of CRs with K8, like ConfigMaps, Secrets, Service,...

**Comment by genevieveluyt** [comment]
Thanks for the additional info! Unfortunately, I don't think we will be adding support for OpenShift in the foreseeable future as we don't use OpenShift and it would be difficult for us to maintain and test. If anyone else would like to add support for OpenShift and it isn't too much of a maintenance burden we would be happy to accept that contribution. That being said, I'm going to close this issue. Sorry about that!
