### ISSUE TITLE
Integration of DeepSource

### ISSUE THREAD

**Issue by withshubh** [Shopify/kubeaudit#318]
Hi :wave: 

I fixed a few code quality issues(PR #315) that were caught by running DeepSource static analysis.

There are a few more performance, bug risk, anti-pattern & security issues that exist in the code. Consider taking a look at the [report generated by DeepSource](https://deepsource.io/gh/withshubh/kubeaudit/). 

I'd suggest you activate the analysis on this repo that will help improve the code quality.

##### Using DeepSource to continuously analyze your repository

- The repo already has the configuration file required to configure analysis settings.
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Activate analysis [here](https://deepsource.io/gh/Shopify/kubeaudit/).

**Comment by withshubh** [comment]
Hey @genevieveluyt :wave:

Please have a look at this issue :sparkling_heart:

**Comment by genevieveluyt** [comment]
The team has decided not to integrate DeepSource.
