### ISSUE TITLE
Add option to get kubeaudit version

### ISSUE THREAD

**Issue by quarkie** [Shopify/kubeaudit#320]
##### ISSUE TYPE
 - [x] Feature Idea
# BUG REPORT
##### SUMMARY
Add option to get kubeaudit version

##### ENVIRONMENT
* Kubeaudit version:kubeaudit-v0.11.8
* Kubeaudit install method: brew and exe for windows

##### STEPS TO REPRODUCE

brew -v
brew --help

##### EXPECTED RESULTS

The current version could be shown

e.g
```
# kubeaudit -v
0.11.8
```

##### ACTUAL RESULTS

I found no way to currently retrieve the version, if there is a way, sry for bringing up this issue :) and i woul kindly ask to show me that way

##### ADDITIONAL INFORMATION

# FEATURE IDEA

maybe add a cmd line option (-v --version) to get the version or output it  on --help

**Comment by genevieveluyt** [comment]
Hey @quarkie , you are right, there is currently no way to get the version directly from kubeaudit. If you're using brew you can get the version using `brew info kubeaudit` but agreed that it would be nice to have built in to kubeaudit.
