### ISSUE TITLE
"ResourceKind":"Pod" --> This seems broken and not giving the right outputs

### ISSUE THREAD

**Issue by secmesh** [Shopify/kubeaudit#321]
##### ISSUE TYPE
 - [x] Bug Report

# BUG REPORT

##### ENVIRONMENT
kubeaudit-v0.11.8
* Kubeaudit install method: Binary installed into a container and run in a pod in a Kubernetes Cluster running Kube version 1.16

##### STEPS TO REPRODUCE

Running Kubeaudit in a pod (or in a MAC laptop) does not produce accurate results for "ResourceKind":"Pod". When i run kubeaudit --format json all, the output for "ResourceKind":"Pod" shows only 1 Namespace whereas there are several namespaces in the cluster. Version 1.0.8 worked perfectly fine though.

##### EXPECTED RESULTS

I expect to see Security context issues at the Pod Level as well. I mainly only see it for Cronjobs, Deployments and Daemonsets in my cluster. Version 1.0.8 throws out the right results, albeit with "Kubetype":"pod" instead of "ResourceKind":"Pod"

##### ACTUAL RESULTS

Returned issues only with 1 namespace's pods

**Comment by genevieveluyt** [comment]
Hi @secmesh, I believe this behaviour was intentionally changed in https://github.com/Shopify/kubeaudit/pull/282. We could potentially bring back the old behaviour with a flag if that is the case.

**Comment by secmesh** [comment]
> Hi @secmesh, I believe this behaviour was intentionally changed in #282. We could potentially bring back the old behaviour with a flag if that is the case.

Thanks for letting me know @genevieveluyt. At my company we have implemented Pod Security policies and the way we've implemented this is by explicitly listing out all the Capabilities that we would like to drop and allow only the required Capabilities. So The Deployments, Cronjobs etc, won't ever see the Capabilities required by the PSP. The Dev only has to "allow" the specified Capability in their manifest and the PSP would grant them access if it is allowed. 

This being the case, the Deployments will never have the "dropped" capabilities and the hence only the individual PODs would see these capabilities as being dropped and only a handful allowed (if ever required). And hence Kubeaudit would always throw up a false positive with regards to Deployments, Crons, Daemonsets etc. So i have to filter it out to only Pod level capabilities which in the new version of Kubeaudit doesn't show up at all and so the filtering fails and i do not get the right outputs.

**Comment by genevieveluyt** [comment]
Since PSPs are deprecated (https://github.com/kubernetes/kubernetes/pull/97171) I don't think this is a flow we should add support for.

**Comment by secmesh** [comment]
Fair enough, although this kinda sucks since teams on cloud platforms such as EKS are going to be way behind 1.21. I'll just use an earlier Kubeaudit binary

**Comment by genevieveluyt** [comment]
Ok I'm going to close this issue for now. If we get more requests for this functionality we can revisit.
