### ISSUE TITLE
Deprecate mountds

### ISSUE THREAD

**Issue by dani-santos-code** [Shopify/kubeaudit#328]
##### ISSUE TYPE
 - [ ] Bug Report
 - [ ] Feature Idea
- [x] Other
##### SUMMARY
With the new `mounts` auditor implementation, we no longer need `mountds` as discussed here: https://github.com/Shopify/kubeaudit/pull/322

It was decided that we should remove `mountds` in favour of `mounts`

This is required so that we can make a new release (0.13.0)

c/c @genevieveluyt @jcbbc

**Comment by genevieveluyt** [comment]
Hey @jcbbc, just confirming you were planning to open a PR to deprecate the `mountds` command? We're wait to release the `mounts` command until that is done.

**Comment by jcbbc** [comment]
> Hey @jcbbc, just confirming you were planning to open a PR to deprecate the `mountds` command? We're wait to release the `mounts` command until that is done.

Hi, no I didn't have a PR ready, I was indeed thinking that you would do it as I don't know how you want to manage the deprecation process.

**Comment by genevieveluyt** [comment]
No problem, just didn't want to double up on work! Thanks for your contributions, we'll handle the deprecation
