### ISSUE TITLE
Include arm64 assets in releases

### ISSUE THREAD

**Issue by iuliancristea** [Shopify/kubeaudit#333]
##### ISSUE TYPE
 - [X] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY

The released assets do not include the `arm64` tarballs. 

##### ADDITIONAL INFORMATION

`arm64` seems to have been added to the list of default architectures for GoReleaser recently in https://github.com/goreleaser/goreleaser/commit/2edebf0029e8c5a873947306ee892f089438795f.

If the default list is used (that is, the architectures aren't specified explicitly in the config), then the releases should be made with a more recent version of GoReleaser that includes the changes.

**Comment by genevieveluyt** [comment]
Hey @iuliancristea , thanks for pointing this out! I've updated goreleaser to make sure new releases will have the arm64 tarball, and I've manually added it to the [latest releast](https://github.com/Shopify/kubeaudit/releases/tag/v0.13.0). Please reopen this issue if you have any problems with it. Cheers
