### ISSUE TITLE
kubeaudit doesn't support initContainers

### ISSUE THREAD

**Issue by genevieveluyt** [Shopify/kubeaudit#355]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY

As pointed out by @thriqon in https://github.com/Shopify/kubeaudit/issues/285#issuecomment-891289275, kubeaudit audits `containers` but not `initContainers`. This is specifically problematic for the `apparmor` auditor which warns if an apparmor annotation refers to a container that doesn't exist and will remove that annotation in `autofix`. Since it ignores `initContainers` this would mean that an apparmor annotation which correctly refers to an `initContainer` would be removed by kubeaudit. In general though, we should add support for kubeaudit to add security controls to `initContainers` the same way it does for `containers`.

##### ENVIRONMENT
See https://github.com/Shopify/kubeaudit/issues/285#issuecomment-891894619

##### STEPS TO REPRODUCE

See https://github.com/Shopify/kubeaudit/issues/285#issuecomment-891894619

##### EXPECTED RESULTS

Kubeaudit should audit `initContainers` the same way it audits `containers`.

##### ACTUAL RESULTS

Kubeaudit ignores `initContainers` and removes apparmor annotations that refer to `initContainers`

##### ADDITIONAL INFORMATION

See https://github.com/Shopify/kubeaudit/issues/285#issuecomment-891894619

**Comment by danishprakash** [comment]
@genevieveluyt I'd like to work on this, would that be okay?
