### ISSUE TITLE
How to fetch Kubeaudit output in text file?

### ISSUE THREAD

**Issue by ridhika1628** [Shopify/kubeaudit#357]
I am trying to run below command

kubeaudit all

Want to get the output in some text file so that if there are "level=error" in auditing will make it as fail.

**Comment by genevieveluyt** [comment]
It looks like you're using an older version of kubeaudit. Can you follow the [installation instructions](https://github.com/Shopify/kubeaudit#installation) to install the latest version of kubeaudit? You'll know you have the right one if you can run the version command:

```
$ kubeaudit version
0.14.2
```

**Comment by genevieveluyt** [comment]
@ridhika1628 do you still need help with this?
