### ISSUE TITLE
kubeaudit using unregistered annotations

### ISSUE THREAD

**Issue by sftim** [Shopify/kubeaudit#457]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
https://github.com/Shopify/kubeaudit lists some annotations that have meaning to kubeaudit. However, these annotations are not registered and kubeaudit is using them without co-ordinating with the Kubernetes project.

Those annotations:
- `container.audit.kubernetes.io/[container name].[override identifier]`
- `audit.kubernetes.io/pod.[override identifier]`

##### ENVIRONMENT
* Kubeaudit version: v0.19.0

##### STEPS TO REPRODUCE

Visit https://kubernetes.io/docs/reference/labels-annotations-taints/ to see list of registered annotations.
Visit https://github.com/Shopify/kubeaudit to see use of these unregistered annotations.

##### ADDITIONAL INFORMATION

People might assume that these annotations are official, but they actually are not.

# FEATURE IDEA

- [ ] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Proposal:*

Either:
- request that the Kubernetes project register these annotations (and see this to its conclusion)
- use a Shopify-owned domain for the label namespace
- use some other domain that Shopify is allowed to use for the label namespace

**Comment by dani-santos-code** [comment]
Thanks a lot for opening this issue @sftim! Your suggestions sound good. c/c @genevieveluyt

**Comment by sftim** [comment]
This is a low impact. Whenever I spot folks using unregistered annotations in the Kubernetes' project's namespace, I ask them to fix it.

**Comment by sftim** [comment]
Oh, also: label keys are not URIs and there's no expectation that they would be. Public label namespaces (the `kubernetes.io` in `kubernetes.io/example-annotations`) _are_ DNS names, and it's polite to use a namespace connected to a domain that exists and doesn't belong to another party.
