### ISSUE TITLE
Audit for (nix) namespaces

### ISSUE THREAD

**Issue by jonpulsifer** [Shopify/kubeaudit#46]
The use of host's networking | `hostNetwork`
The use of host’s PID namespace | `hostPID`
The use of host’s IPC namespace | `hostIPC`

**Comment by jinankjain** [comment]
@JonPulsifer you mean auditing for specific namespaces?

**Comment by natalysheinin** [comment]
We want to audit against these keys being used.
https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#pod-v1-core
