### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by Ser87ch** [Shopify/kubeaudit#487]
Could you please release a new version of kubeaudit?

**Comment by Ser87ch** [comment]
@dani-santos-code , @genevieveluyt could you help with the release?

**Comment by dani-santos-code** [comment]
Hi, @Ser87ch ! Thank you for the reminder and the request. We'll need to test it a bit more and see exactly what will break with the changes to add to the summary of the release (changelog). We'll be dropping support for whoever is using the old seccomp annotations. We'll keep you posted once we have an update, likely by the end of next week.

**Comment by Ser87ch** [comment]
Thanks for the update.

**Comment by dani-santos-code** [comment]
@Ser87ch starting the release process now

**Comment by dani-santos-code** [comment]
A new release has been made. See: https://github.com/Shopify/kubeaudit/releases/tag/v0.21.0

thank you ever so much for you amazing contributions @Ser87ch !!! We really appreciate it!! 👏 👏 👏 👏
