### ISSUE TITLE
Refactor all commands

### ISSUE THREAD

**Issue by klautcomputing** [Shopify/kubeaudit#50]
After #48, we can now refactor the commands even further take a look at: https://github.com/Shopify/kubeaudit/blob/master/cmd/runAsNonRoot.go#L56-L81
the same code will show up in basically all the commands and could be refactored into one function in `cmd/util.go` which additionally takes a function pointer as a parameter and then just calls that function in https://github.com/Shopify/kubeaudit/blob/master/cmd/runAsNonRoot.go#L79

**Comment by jinankjain** [comment]
This can also be closed with #64 @klautcomputing @fedorlis
