### ISSUE TITLE
Another refactor issue

### ISSUE THREAD

**Issue by klautcomputing** [Shopify/kubeaudit#51]
The code here https://github.com/Shopify/kubeaudit/blob/master/cmd/runAsNonRoot.go#L78-L80
should be refactored to something like this:
```
	var results []Result
	for _, resource := range resources {
		results = append(results, auditRunAsNonRoot(resource))
	}
```
Why I am I saying something like that? Because we want to keep the `go` and that might require channels.
We want to do this because the print here https://github.com/Shopify/kubeaudit/blob/master/cmd/runAsNonRoot.go#L36-L38 is totally out of place and the `audit` functions get used in other places where the printing doesn't make sense.
Obviously, the print needs be put back in, e.g.
```
	var results []Result
	for _, resource := range resources {
		results = append(results, auditRunAsNonRoot(resource))
	}
	for _, result := range results {
		result.Print()
	}
```

pardon my pseudo code

**Comment by jinankjain** [comment]
I think this issue can be closed now with #64 @klautcomputing @fedorlis
