### ISSUE TITLE
0.22.0 release

### ISSUE THREAD

**Issue by chenrui333** [Shopify/kubeaudit#537]
##### ISSUE TYPE
 - [x] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
👋 Looks like the 0.22.0 release did not get completed, thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/125542

**Comment by chenrui333** [comment]
It would be good to not re-tag the release as well.

relates to:
- Homebrew/homebrew-core#126306
- Homebrew/homebrew-core#125542

**Comment by genevieveluyt** [comment]
Hi @chenrui333 I'm actually not sure we can complete the release in the state it was tagged. I think we may need to skip that version and release the next version with the [new release process](https://github.com/Shopify/kubeaudit/pull/539). @chenrui333 is that a problem for brew? @dani-santos-code wdyt?

**Comment by chenrui333** [comment]
close via the recent releases

![image](https://github.com/Shopify/kubeaudit/assets/1580956/b849724c-b5da-4e7e-8289-22d9bf5c3c0e)
