### ISSUE TITLE
Make golint happy

### ISSUE THREAD

**Issue by klautcomputing** [Shopify/kubeaudit#55]
https://goreportcard.com/report/github.com/Shopify/kubeaudit#golint

**Comment by jinankjain** [comment]
Same goes for https://goreportcard.com/report/github.com/Shopify/kubeaudit#go_vet

**Comment by natalysheinin** [comment]
Adding some context/references:

- golint points out styling suggestions (not necessarily gold standard) https://github.com/golang/lint
- the suggestions we got int he goreportcard for golint are mainly related to exported types not having a comment 
- the comments serve their purpose for Godoc (which parses Golang and produces HTML easy-to-use documentation) 
- Here is the result of our Godoc: https://godoc.org/github.com/Shopify/kubeaudit/cmd
