### ISSUE TITLE
Add support for apps/v1beta2

### ISSUE THREAD

**Issue by jinankjain** [Shopify/kubeaudit#70]
Since in k8s 1.8 some of the resources moved to apps/extensions v1beta2. We should support auditing against those cases too. For more context: https://kubernetes.io/docs/reference/workloads-18-19/

**Comment by klautcomputing** [comment]
I tagged it for the next release candidate :)

**Comment by johscheuer** [comment]
This is actually implemented: https://github.com/Shopify/kubeaudit/blob/master/cmd/types.go#L106 so we could close this issue?
